### ISSUE TITLE
No tar files for installation

### ISSUE THREAD

**Issue by nabw** [KarypisLab/ParMETIS#19]
Dear developers, 

For some time now, it seems impossible to access the Karypis lab page, so there are no tar files for installing metis/parmetis. Is this a design choice or is there a problem with hosting? I have problems with some automated installation procedures, so please let me know if this will stay like this to work on the relevant changes. 

Best regards

**Comment by leofang** [comment]
xref: https://github.com/KarypisLab/METIS/issues/39

**Comment by nabw** [comment]
Hi all, the site is up again, so this issue can be safely closed:

https://github.com/KarypisLab/METIS/issues/37#issuecomment-1242798685
