### ISSUE TITLE
Is or not close restraint the edge input in dgl branch ?

### ISSUE THREAD

**Issue by lixusign** [KarypisLab/ParMETIS#2]
148190521 412588954 5258249 4 10.0 
33433558 412588954 46718668 4 10.0 
187827069 412588954 34871987 14 1.0 
7741868 412588954 25764335 6 1.0 
788146 412588954 2525129 6 1.0 
90390322 412588954 55706994 4 10.0
128984342 412588954 38946256 4 10.0
28125126 412588954 39373577 4 10.0

In my edge input file format like before,   not like a ordered file as follow 

1196825 458 0
  421 1198055 459 0
   424 1200642 460 0
   425 1198095 461 0
   426 1198459 462 0
   427 1195850 463 0
   428 1196537 464 0
   430 1201660 465 0
   431 1197523 466 0

Excuse me, what is the impact of the bug will produce

**Comment by karypis** [comment]
If the question is about ordering of the edges in the _edges.txt file, the answer is no. You can provide the edges in any order.
